# Generated by Django 2.0.2 on 2018-03-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180304_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='additional_literature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='main_literature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='postrekvisit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
