# Generated by Django 2.0.2 on 2018-03-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180305_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literature_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('izdanie', models.CharField(max_length=100)),
                ('stranica', models.CharField(max_length=100)),
                ('god', models.CharField(max_length=100)),
                ('typee', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Takyryp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takyryp_aty', models.CharField(max_length=100)),
                ('opisanie', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='additional_literature',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='main_literature',
        ),
        migrations.AddField(
            model_name='subject',
            name='literature',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='catalog.Literature'),
        ),
        migrations.AddField(
            model_name='subject',
            name='takyryp',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='catalog.Takyryp'),
        ),
    ]
