# Generated by Django 2.0.2 on 2018-03-07 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180306_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zert_jumys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('opisanie', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='takyryp',
            name='zert_jumys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Zert_jumys'),
        ),
    ]
