# Generated by Django 2.0.2 on 2018-03-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180307_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='takyryp',
            name='number',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
