# Generated by Django 2.0.2 on 2018-04-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_takyryp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zert_jumys',
            name='opisanie',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
