# Generated by Django 2.0.2 on 2018-04-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180403_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='literature_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
