# Generated by Django 2.0.2 on 2018-04-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180417_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='typee',
            field=models.CharField(blank=True, choices=[('Н', 'Негізгі'), ('Қ', 'Қосымша')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
