# Generated by Django 2.0.2 on 2018-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180417_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='literature',
            name='god',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='literature',
            name='izdanie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='literature',
            name='stranica',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
