# Generated by Django 2.0.2 on 2018-04-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20180417_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='literature',
            name='god',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='literature',
            name='izdanie',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='literature',
            name='stranica',
            field=models.CharField(default='', max_length=100),
        ),
    ]
