# Generated by Django 2.0.2 on 2018-04-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20180417_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='literature',
            name='god',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='literature',
            name='izdanie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='literature',
            name='stranica',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
