# Generated by Django 2.0.2 on 2018-04-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20180417_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='postrekvisit',
        ),
    ]
