# Generated by Django 2.0.2 on 2018-04-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remove_subject_postrekvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apta', models.CharField(blank=True, max_length=100)),
                ('lekcia', models.CharField(blank=True, max_length=100)),
                ('zert', models.CharField(blank=True, max_length=100)),
                ('adebiet', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
