# Generated by Django 2.0.2 on 2018-04-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_keste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keste',
            name='adebiet',
        ),
        migrations.AlterField(
            model_name='keste',
            name='apta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keste',
            name='lekcia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='keste',
            name='zert',
            field=models.CharField(max_length=100),
        ),
    ]
