# Generated by Django 2.0.2 on 2018-04-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20180419_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literature',
            old_name='god',
            new_name='godd',
        ),
    ]
