# Generated by Django 2.0.2 on 2018-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20180419_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='godd',
            field=models.DateField(blank=True, default='1997-05-05', null=True),
        ),
    ]
