# Generated by Django 2.0.2 on 2018-04-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20180419_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literature',
            old_name='godd',
            new_name='god',
        ),
    ]
