# Generated by Django 2.0.2 on 2018-04-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20180419_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literature',
            name='god',
        ),
    ]
