# Generated by Django 2.0.2 on 2018-04-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_remove_literature_god'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='god',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
