# Generated by Django 2.0.2 on 2018-04-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20180419_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='literature',
            name='god',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='literature',
            name='izdanie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='literature',
            name='stranica',
            field=models.CharField(max_length=100),
        ),
    ]
